const assert = require('node:assert/strict');
const fs = require('node:fs');

const html = fs.readFileSync('public/chat.html', 'utf8');
assert.match(html, /fetch\('\/api\/chat'/);
assert.match(html, /const responseText = await r\.text\(\)/);
assert.match(html, /if \(!r\.ok\) throw new Error/);
assert.match(html, /หมดเวลารอเซิร์ฟเวอร์/);
assert.match(html, /\.img-msg \{ display: block;/);
assert.match(html, /<style id="gemini-mobile-ui">/);
assert.match(html, /height:100dvh/);
assert.match(html, /env\(safe-area-inset-bottom\)/);
assert.match(html, /\.composer-tools \.ptt \{ display:flex !important;/);
assert.match(html, /<style id="mobile-viewport-hardening">/);
assert.match(html, /width:100vw !important/);
assert.match(html, /transform:none !important/);
const server = fs.readFileSync('server.js', 'utf8');
assert.match(server, /Cache-Control.*no-store/);
assert.match(server, /app\.use\(express\.static\([^\n]+/);
assert.doesNotMatch(html, /ได้เลยค่ะที่รัก!.*พร้อมรับฟังเสมอ/, 'chat must not use the canned mock response from pasted content');
console.log('chat send regression tests passed');
