from pathlib import Path
p=Path('/home/ubuntu/silelo-neo-connect/public/chat.html')
s=p.read_text()
needle="        if (tree) tree.querySelectorAll('[data-gh-file]').forEach(function(btn) {"
start=s.find(needle)
if start < 0: raise SystemExit('github read handler not found')
end=s.find('\n', start)
if end < 0: raise SystemExit('github handler line not terminated')
new="""        if (tree) tree.querySelectorAll('[data-gh-file]').forEach(function(btn) { btn.addEventListener('click', async function() { var path = decodeURIComponent(btn.getAttribute('data-gh-file')); var fr = await fetch('/api/github/file?' + ghParams({ path: path })); var fj = await fr.json(); var pre = document.getElementById('ghFile'); if (!pre) return; pre.style.display = 'block'; if (!fj.ok || !fj.file) { pre.textContent = '❌ ' + (fj.error || 'อ่านไฟล์ไม่ได้'); return; } if (fj.file.content === null) { pre.textContent = '📄 ' + fj.file.path + '\\n\\n(binary file — เปิดดูได้จาก GitHub แต่แก้ผ่าน editor นี้ไม่ได้)'; return; } pre.innerHTML = '<div style=\"display:flex;gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap\"><strong>📄 ' + escHtml(fj.file.path) + '</strong><input id=\"ghCommitMsg\" value=\"Update ' + escAttr(fj.file.path) + '\" style=\"flex:1;min-width:220px;padding:8px;border-radius:8px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);color:var(--txt)\"><button class=\"ct-btn\" id=\"ghSaveFile\">💾 Commit ไป GitHub</button></div><textarea id=\"ghEditor\" spellcheck=\"false\" style=\"width:100%;min-height:360px;padding:12px;border-radius:10px;border:1px solid rgba(255,255,255,.12);background:rgba(0,0,0,.3);color:var(--txt);font:12px/1.55 ui-monospace,monospace;white-space:pre;resize:vertical\"></textarea>'; var ed = document.getElementById('ghEditor'); ed.value = fj.file.content || ''; document.getElementById('ghSaveFile').onclick = async function() { if (!confirm('ยืนยันเขียนไฟล์จริงและสร้าง commit บน GitHub?')) return; var save = document.getElementById('ghSaveFile'); save.disabled = true; save.textContent = '⏳ กำลัง commit...'; try { var wr = await fetch('/api/github/file', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ owner: document.getElementById('ghOwner').value.trim(), repo: document.getElementById('ghRepoName').value.trim(), ref: document.getElementById('ghRef').value, path: fj.file.path, message: document.getElementById('ghCommitMsg').value.trim() || ('Update ' + fj.file.path), content: ed.value }) }); var wj = await wr.json().catch(function() { return {}; }); if (!wr.ok || !wj.ok) throw new Error(wj.error || 'commit ไม่สำเร็จ'); save.textContent = '✅ Commit แล้ว'; ghMsg('บันทึก ' + fj.file.path + ' ไป GitHub แล้ว', false); } catch (e) { save.disabled = false; save.textContent = '💾 Commit ไป GitHub'; ghMsg('❌ ' + e.message, true); } }; }); });"""
p.write_text(s[:start] + new + s[end:])
print('github editor enabled')
